services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
